### ISSUE TITLE
SP subir recetas, la tabla de recetas en el DER no tiene instrucciones, ver si lo agregamos o lo sacamos en el sp

### ISSUE THREAD

**Issue by tusar-verma** [lbotano/recetasdivertidas#11]

**Comment by lbotano** [comment]
¿Por qué sacarlo?
El problema es que el que hizo el der se olvidó de poner varias columnas de `Receta`

**Comment by tusar-verma** [comment]
ta bien, yo habia interpretado que la descripción de la receta incluia las instrucciones de la receta, por eso decia de sacarlo
