### ISSUE TITLE
Deberiamos hacer que spAgregarIngrediente y spAsignarCategoriaIngrediente sean un mismo procedure

### ISSUE THREAD

**Issue by tusar-verma** [lbotano/recetasdivertidas#12]
Podemos hacer que sea con una TRANSACTION y si se sube el ingrediente pero no se le pudo asignar las categorias, que se haga un rollback.
O (mucho mas simple y facil xd) que ambos procedures sean uno solo, y paso desde el servidor un json con las categorias del ingrediente

**Comment by lbotano** [comment]
Solucionado
