### ISSUE TITLE
SP que faltan

### ISSUE THREAD

**Issue by tusar-verma** [lbotano/recetasdivertidas#14]
### Para admin

- [x]  **borrar categoria de ingrediente**
- [x]  **borrar categoria de receta**
- [x]  **borrar receta**

### Para cliente

- [x] **consulta de recetas por categoria de recetas**
- [x] **consulta de recetas por categoría de ingredientes**
- [x] **listar categorias de recetas**
- [x] **listar categorias de ingredientes**
- [x] **Preguntas de seguridad**
- [x] **Reiniciar la contraseña con pregunta de seguridad**

**Comment by lbotano** [comment]
Creo que sería mejor obtener una lista de las categorías de recetas e ingredientes haciendo selects directamente.

Lo de preguntas de seguridad no entiendo que es. ¿Sería un procedure para validar que el usuario puede cambiar la contraseña o qué?

**Comment by lbotano** [comment]
Otra cosa es qué hacer con las foreign keys cuando se borre una categoría.
