### ISSUE TITLE
Implementar mensajes de cliente a servidor

### ISSUE THREAD

**Issue by lbotano** [lbotano/recetasdivertidas#2]
- [x] **BORRARRECUSU:** Eliminar una receta
```
BORRARRECUSU
<rID> (ID de la receta)
<nickname> (nickname del usuario que esta borrando la receta)
```

- [x] **CALIFICAR:** Calificar receta
```
CALIFICAR
<nickname>
<idReceta>
<calificacion>
```

- [x] **CAMBIARCONTRA** cambiar contraseña 
```
CAMBIARCONTRA
<nickname> (nickname del usuario que solicita el cambio de contraseña)
<respuesta> (respuesta de la pregunta de seguridad)
<contraNueva> 
```

- [x] **CONSCALIFUSUARIO** Obtiene la calificacion que le hizo un usuario a una receta.
```
CONSCALIFUSUARIO
<nickname> (nickname del usuario del cual se quiere sabér qué calificación puso)
<rID> (id de la receta)
```

- [x] **CONSRECETASCATING** Envía IDs de categorías de ingrediente y espera los nombres e IDs de las recetas que cumplan
```
CONSRECETASCATING
<numpag> (numero de pagina de la consulta, para no mandar todas las id de las recetas, se separa por paginas)
<cID> (id de la categoría de ingrediente)
...
<cID> (id de la categoría de ingrediente)
```

- [x] **CONSRECETASCATREC** Envía IDs de categorías de recetasy espera los nombres e IDs de las recetas que cumplan
```
CONSRECETASCATREC
<numpag> (numero de pagina de la consulta, para no mandar todas las id de las recetas, se separa por paginas)
<cID> (id de la categoría de recetas)
...
<cID> (id de la categoría de recetas)
```

- [x] **CONSRECETAING:** Envía IDs de ingredientes y espera los nombres e IDs de las recetas que correspondan a los ingredientes.
```
CONSRECETAING
<numpag> (numero de pagina de la consulta, para no mandar todas las id de las recetas, se separa por paginas)
<iID> (id del ingrediente)
…
<iID> (id del ingrediente)
```

- [x] **CONSRECETATEXT:**  Buscar recetas en base a texto
```
CONSRECETATEXT
<numpag> (numero de pagina de la consulta, para no mandar todas las id de las recetas, se separa por paginas)
<texto> (texto que ingresa el usuario para realizar la búsqueda)
```

- [x] **CONSTOPRECETAS:** Mostrar las mejores recetas
```
CONSTOPRECETAS
<numpag> (número de página de la consulta, empieza por 0)
```

- [x] **DATOSRECETA:** Envía el ID de una receta y recibe sus datos.
```
DATOSRECETA
<rID>
```

- [x] **INGREDIENTES** Request para una lista de los ingredientes con sus ids
```
INGREDIENTES
```

- [x] **LISTARCATREC:** Lista las categorías de las recetas.
```
LISTARCATREC
```

- [x] **LISTARCATING:** Lista las categorías de los ingredientes.
```
LISTARCATING
```

- [x] **LOGIN:** Loguearse con un usuario
```
LOGIN
<nickname>
<contraseña>
```

- [x] **PREGUNTASSEG:** Petición de las preguntas de seguridad para el registro de usuarios
```
PREGUNTASSEG
```

- [x] **RECETASDEUSUARIO:** Le pide al server las recetas de un usuario enviado como parametro
```
RECETASDEUSUARIO
<nickname>
```

- [x] **REGISTRO:** Registrar usuario
```
REGISTRO
<nickname>
<preguntaSeguridad>
<respuestaSeguridad>
<uNombre>
<uApellido>
<uContrasenia>
<uGenero>
<uMail>
```

- [x] **SERVIDORVIVE**
```
SERVIDORVIVE
```

- [x] **SUBIRRECETA:** Subir receta
```
SUBIRRECETA
<rNombre> (nombre de la receta)
<rDescripcion> (descripción de la receta)
<Instrucciones> (instrucciones de la receta)
<iID> (id del ingrediente)
<cantidad>
<unidad>
...
<iID>
<cantidad>
<unidad>
CATEGORIASRECETA
<cID> (id categoria receta)
...
<cID>
INICIOMULTIMEDIA
<mLink>
...
<mLink>
```

- [x] **USUPREGSEG** Pide al servidor la pregunta de seguridad de un usuario pasado como parámetro
```
USUPREGSEG
<nickname>
```

**Comment by camilo-laruffa** [comment]
![image](https://user-images.githubusercontent.com/65632244/100480454-134bd600-30d0-11eb-83e9-f5644aac5d24.png)
