### ISSUE TITLE
La busqueda por texto tiene q buscar tambien en las categorias e ingredientes

### ISSUE THREAD

**Issue by tusar-verma** [lbotano/recetasdivertidas#51]
Modificar el sp de busqueda por texto

**Comment by lbotano** [comment]
Lo voy a hacer cuando esté preparado lo básico del proyecto ya que provisoriamente se pueden hacer por separado esas búsquedas.

**Comment by lbotano** [comment]
No va a haber tiempo para hacer esto y no es muy útil.
