### ISSUE TITLE
Bug en la interfaz de admin

### ISSUE THREAD

**Issue by tusar-verma** [lbotano/recetasdivertidas#63]
Al seleccionar varios items del checkcombobox de subir ingrediente de la interfaz del admin, corre el text field del nombre del ingrediente hasta hacerlo tan chico que no se puede leer lo que se escribe en él

![image](https://user-images.githubusercontent.com/45916892/99432117-78424780-28ea-11eb-9d46-664deca89b60.png)

**Comment by camilo-laruffa** [comment]
😎 ya lo arreglo

**Comment by camilo-laruffa** [comment]
Ya lo arreglé
😎
