### ISSUE TITLE
El servidor manda repetidas veces los ingredientes.

### ISSUE THREAD

**Issue by lbotano** [lbotano/recetasdivertidas#71]
El SP para obtener todos los ingredientes devuelve también sus categorías de esta forma:
|`id_ingrediente`|`id_categoria`|
|--------------------|-------------------|
| 1                     | 1                   |
| 1                     | 2                   |
| 2                     | 2                   |
| 3                     | 1                   |
| 3                     | 3                   |

El servidor no maneja bien esto, y en el caso de la tabla anterior, al cliente se le devolvería esto:
|`id_ingrediente`|
|---|
| 1 |
| 1 |
| 2 |
| 3 |
| 3 | 

Cuando se tendría que devolver realmente:
|`id_ingrediente`|
|---|
| 1 |
| 2 |
| 3 |

**Comment by tusar-verma** [comment]
No se le debería devolver tambien las categorias? 

Camilo habia pedido que el listado de ingredientes devuelva los datos del ingrediente con sus categorias ( issue #43)

Esto es lo que recibe el cliente cuando manda la petición "INGREDIENTES"

![image](https://user-images.githubusercontent.com/45916892/99962662-57a54200-2d6f-11eb-8283-df8f1a6b696b.png)

**Comment by lbotano** [comment]
Hubo malentendido.
