### ISSUE TITLE
Bug visual en la ventana de información de una receta

### ISSUE THREAD

**Issue by tusar-verma** [lbotano/recetasdivertidas#73]
Aparece la calificación promedio y la cantidad de calificaciones juntas

![image](https://user-images.githubusercontent.com/45916892/99968941-94c20200-2d78-11eb-935f-7a376096f5b7.png)

¿Qué es el 5 al lado del titulo?

**Comment by lbotano** [comment]
> ¿Qué es el 5 al lado del titulo?

![Good question](https://en.meming.world/images/en/thumb/0/03/Good_Question.jpg/300px-Good_Question.jpg)

**Comment by camilo-laruffa** [comment]
![image](https://user-images.githubusercontent.com/65632244/100008546-58a89480-2dac-11eb-81c3-20c50d6702a2.png)
Fear no more my peasants, the issue has been thrown into the claws of the abyss
but it is needed for me to say
i do not know the hidden meaning of the five
