### ISSUE TITLE
BUG MANZANAS;MELONES???????????

### ISSUE THREAD

**Issue by tusar-verma** [lbotano/recetasdivertidas#74]
Cuando abris cualquier receta aparece que tiene esos dos ingredientes (wtf??)

![image](https://user-images.githubusercontent.com/45916892/99970011-02baf900-2d7a-11eb-94fd-d33a4d75074f.png)

![image](https://user-images.githubusercontent.com/45916892/99970093-21b98b00-2d7a-11eb-829d-83509ddf7965.png)

En la base de datos dice que tienen estos ingredientes
![image](https://user-images.githubusercontent.com/45916892/99970131-3138d400-2d7a-11eb-8b29-5d2e11310768.png)

**Comment by camilo-laruffa** [comment]
eso es porque "manzanas;melones" son los placeholders de ingredientes xd

**Comment by lbotano** [comment]
Solucionado. Aunque faltan muchas cosas de ver receta.
