### ISSUE TITLE
Hacer que el admin pueda borrar las recetas

### ISSUE THREAD

**Issue by lbotano** [lbotano/recetasdivertidas#80]

**Comment by tusar-verma** [comment]
El borrar receta de admin ahora está hecho de tal forma que el admin tiene que ingresar el nombre de la receta en un textbox:
![image](https://user-images.githubusercontent.com/45916892/100453705-2d6ac180-309a-11eb-8d89-b949250dec16.png)

Deberia ser que cuando abris una receta y sos admin, deberias tener el boton de borrar y utilice los mensajes de admin para borrar recetas. Porque si el usuario escribe un nombre de una receta en chino y va a estar dificil borrarlo xd

![image](https://user-images.githubusercontent.com/45916892/100453870-85a1c380-309a-11eb-8e6a-25ac7da1b5a6.png)

**Comment by camilo-laruffa** [comment]
![image](https://user-images.githubusercontent.com/65632244/100480378-d97acf80-30cf-11eb-95ee-acc59c47a8a6.png)
