### ISSUE TITLE
Problerma cuando abris una imagen de una receta

### ISSUE THREAD

**Issue by tusar-verma** [lbotano/recetasdivertidas#85]
Subi esta imagen:
![image](https://user-images.githubusercontent.com/45916892/100515994-599c4600-315f-11eb-90cc-718d2fb17b06.png)

Cuando le hago click ellla en el programa, me aparece una parte recortada:
![image](https://user-images.githubusercontent.com/45916892/100516010-789ad800-315f-11eb-9bbc-ea2ec6ddee4f.png)

Aunque agrande la pantalla no se llega a ver toda la foto
![image](https://user-images.githubusercontent.com/45916892/100516029-89e3e480-315f-11eb-9fdd-925ec160c06b.png)

Se deberia poner para que puedas scrollear

**Comment by camilo-laruffa** [comment]
Ya ta, ahora podes scrollear en la imagen, asi que deberias poder ver todo
